// <auto-generated />
namespace code.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialScript : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialScript));
        
        string IMigrationMetadata.Id
        {
            get { return "202306131003536_initialScript"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
